name: CI/CD for Hangman Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests-and-coverage:
    name: Unit Tests & Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Dependencies
        run: |
          npm install
          cd hangman-backend && npm install

      - name: Run Backend Tests
        run: npm run test:backend

      - name: Upload Backend Coverage
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: hangman-backend/coverage

  e2e-tests:
    name: E2E Acceptance Tests
    needs: [unit-tests-and-coverage]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Dependencies
        run: |
          npm install
          npm install -g @angular/cli
          npm install -g wait-on
          cd hangman-frontend && npm install
          cd ../hangman-backend && npm install

      - name: Start Applications and Run E2E Tests
        run: |
          # Iniciar backend
          cd hangman-backend && npm run start

          # Iniciar frontend
          cd ../hangman-frontend && npm run start &
          wait-on http://localhost:4200 -t 5000

          # Ejecutar tests e2e
          cd .. && npm run test:e2e
