name: CI/CD for Hangman Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests-and-coverage:
    name: Unit Tests & Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Dependencies
        run: |
          npm install
          cd hangman-backend && npm install

      - name: Run Backend Tests
        run: npm run test:backend

      - name: Upload Backend Coverage
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: hangman-backend/coverage

  e2e-tests:
    name: E2E Acceptance Tests
    needs: [unit-tests-and-coverage]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Dependencies
        run: |
          npm install
          npm install -g @angular/cli
          cd hangman-frontend
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps
          npm install -D cypress
          cd ../hangman-backend && npm install

      - name: Run E2E Tests
        run: |
          # Start backend
          npm run start:backend & 
          sleep 10
          
          # Start frontend
          cd hangman-frontend
          NODE_OPTIONS=--openssl-legacy-provider ng serve & 
          sleep 45
          
          # Run Cypress (usando la ruta correcta)
          cd hangman-frontend && npx cypress run
